version: '3.6'

services:
  # Daftar container yang akan kita buat secara bersamaan
volumes:
  # Volume digunakan untuk menyimpan data ( persistance ) kasus kali ini untuk menyimpan data di database
  db-data:
